springdoc:
  version: 1.0.0
  email: zaruous@naver.com
  desc: Gargoyle Service
  url: 
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true